"""fix: userid change to user_id

Revision ID: 43b23c73035b
Revises: 0ba073468afc
Create Date: 2025-11-03 11:33:03.006101

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "43b23c73035b"
down_revision: Union[str, None] = "0ba073468afc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "query_logs", sa.Column("user_id", sa.String(length=75), nullable=False)
    )
    op.create_index(
        op.f("ix_query_logs_user_id"), "query_logs", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_query_logs_user_id"), table_name="query_logs")
    op.drop_column("query_logs", "user_id")
    # ### end Alembic commands ###
