"""feat: websearch rate limits

Revision ID: 597f5c4be67e
Revises: b9642f45db1d
Create Date: 2025-07-28 09:40:04.424627

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "597f5c4be67e"
down_revision: str | None = "b9642f45db1d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("web_search_ratelimit_day", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("web_search_ratelimit_hour", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("web_search_ratelimit_minute", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "web_search_ratelimit_minute")
    op.drop_column("users", "web_search_ratelimit_hour")
    op.drop_column("users", "web_search_ratelimit_day")
    # ### end Alembic commands ###
