"""feat: new user config and web rate limits

Revision ID: 9ddf28cf6b6f
Revises: 597f5c4be67e
Create Date: 2025-09-10 15:28:47.830669

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9ddf28cf6b6f"
down_revision: str | None = "597f5c4be67e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("query_logs", sa.Column("web_search_calls", sa.Integer(), nullable=False))
    op.add_column("users", sa.Column("rate_limits", sa.JSON(), nullable=True))
    op.drop_column("users", "web_search_ratelimit_minute")
    op.drop_column("users", "web_search_ratelimit_day")
    op.drop_column("users", "ratelimit_minute")
    op.drop_column("users", "ratelimit_day")
    op.drop_column("users", "ratelimit_hour")
    op.drop_column("users", "web_search_ratelimit_hour")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "web_search_ratelimit_hour",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column("ratelimit_hour", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("ratelimit_day", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("ratelimit_minute", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("web_search_ratelimit_day", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users",
        sa.Column(
            "web_search_ratelimit_minute",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("users", "rate_limits")
    op.drop_column("query_logs", "web_search_calls")
    # ### end Alembic commands ###
