"""fix: remove mail and adjust field lengths

Revision ID: ca76e3ebe6ee
Revises: da89d3230653
Create Date: 2025-04-25 09:08:37.775973

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ca76e3ebe6ee"
down_revision: str | None = "da89d3230653"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "query_logs",
        "userid",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=75),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "userid",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=75),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "apikey",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=75),
        existing_nullable=False,
    )
    op.drop_index("ix_users_email", table_name="users")
    op.drop_index("ix_users_apikey", table_name="users")
    op.create_index(op.f("ix_users_apikey"), "users", ["apikey"], unique=False)
    op.drop_column("users", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_users_apikey"), table_name="users")
    op.create_index("ix_users_apikey", "users", ["apikey"], unique=True)
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.alter_column(
        "users",
        "apikey",
        existing_type=sa.String(length=75),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "userid",
        existing_type=sa.String(length=75),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "query_logs",
        "userid",
        existing_type=sa.String(length=75),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
