# Disable automatic HTTPS and use HTTP only
{
        auto_https off
        default_bind 0.0.0.0
}

# Use :80 explicitly to force HTTP-only behavior
:80 {
	handle_path /nuc/* {
		uri strip_prefix /nuc
		reverse_proxy nilai-nuc-api:8080
	}

	handle_path /testnet/* {
		uri strip_prefix /testnet
		reverse_proxy testnet-nilai-nuc-api:8080
	}

	handle {
		reverse_proxy nilai-api:8080
	}
}
